##
# This config file connects to the postgres install from a rancher desktop instance.
# Use the flag '-Dgrails.env=rancher-desktop-db' when running
##

dataSource:
  dbCreate: none
  url: "jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.database:okapi_modules_test}" # Port 5432 forwarded so as not to clash.
  username: postgres
  password: pa55w0rd
  driverClassName: org.postgresql.Driver
  dialect: com.k_int.hibernate.dialects.postgres.KIPostgres94Dialect
  schemaHandler: com.k_int.okapi.OkapiSchemaHandler
  logSql: false
  properties:
      jmxEnabled: false
      maximumPoolSize: ${db.maxpoolsize:50}
      transactionIsolation: TRANSACTION_READ_COMMITTED

  hibernate:
    enable_lazy_load_no_trans: true

okapi: 
  service:
    host: localhost
    port: 30100
logging:
  config: classpath:logback-development.xml

concurrentJobsGlobal: "${CONCURRENT_JOBS_GLOBAL:3}"

endpoints:
  include-stack-trace: true # This being true for dev builds allows us to see stacktraces in the responses

# BF Sunflower folio client config override
accesscontrol:
  folio:
    baseokapiurl: "https://kong-bugfest-sunflower.int.aws.folio.org"
    tenantname: "fs09000000"
    patronid: "9eb67301-6f6e-468f-9b1a-6134dc39a684"
    userlogin: "folio"
    userpassword: "folio"
  acqunits:
    enabled: true

# Eureka Snapshot folio client config override
#accesscontrol:
#  folio:
#    baseokapiurl: "https://folio-etesting-snapshot-kong.ci.folio.org"
#    tenantname: "diku"
#    patronid: "7d17383e-c8b5-40ab-a0a3-4a06a1bff3e1" # THIS WILL CHANGE DAILY
#    userlogin: "diku_admin"
#    userpassword: "admin"

#    register: true
#    deploy: true

# Snapshot folio client config override
#accesscontrol:
#  folio:
#    baseokapiurl: "https://folio-snapshot-okapi.dev.folio.org" # SNAPSHOT
#    #baseokapiurl: "https://folio-snapshot-2-okapi.dev.folio.org" # SNAPSHOT 2
#    tenantname: "diku"
#    #patronid: "6d4357a4-6237-594c-a3f5-fb5847eeba26" # THIS WILL CHANGE DAILY
#    patronid: "defaultPatronId" ## Current bug... is this causing issues?
#    userlogin: "diku_admin"
#    userpassword: "admin"
#  acqunits:
#    enabled: true

